version: '3'

networks:
  web_network:
    # external: true
    driver: bridge
  db_archive_network:
    driver: bridge
  db_token_contracts_network:
    driver: bridge
  db_token_activity_network:
    driver: bridge

services:
  mongo-archive:
    image: mongo:latest
    volumes:
      - ../mongodb/archive/:/data/db/
    ports:
      - '5000:27017'
    networks:
      - db_archive_network

  mongo-token-contracts:
    image: mongo:latest
    volumes:
      - ../mongodb/token-contracts/:/data/db/
    ports:
      - '5001:27017'
    networks:
      - db_token_contracts_network

  mongo-token-activity:
    image: mongo:latest
    volumes:
      - ../mongodb/token-activity/:/data/db/
    ports:
      - '5002:27017'
    networks:
      - db_token_activity_network

  indexer-archive:
    build:
      context: .
      target: archive
    ports:
      - 4050
    restart: unless-stopped
    volumes:
      - ./indexers/archive/last-indexed-block:/base/indexers/archive/last-indexed-block
    environment:
      MONGO_URI: mongodb://mongo-archive:27017/archive
      PORT: 4050
    depends_on:
      - mongo-archive
    networks:
      - db_archive_network
      - web_network

  indexer-token-contracts:
    build:
      context: .
      target: token-contracts
    ports:
      - 4051
    restart: unless-stopped
    volumes:
      - ./indexers/token-contracts/last-indexed-block:/base/indexers/token-contracts/last-indexed-block
    environment:
      ARCHIVE_GRAPH: http://indexer-archive:4050/graphql
      PORT: 4051
      MONGO_URI: mongodb://mongo-token-contracts:27017/token-contracts
    depends_on:
      - indexer-archive
      - mongo-token-contracts
    networks:
      - db_token_contracts_network
      - web_network

  indexer-token-activity:
    build:
      context: .
      target: token-activity
    ports:
      - 4052
    restart: unless-stopped
    volumes:
      - ./indexers/token-activity/last-indexed-block:/base/indexers/token-activity/last-indexed-block
    environment:
      ARCHIVE_GRAPH: http://indexer-archive:4050/graphql
      CONTRACT_GRAPH: http://indexer-token-contracts:4051/graphql
      MONGO_URI: mongodb://mongo-token-activity:27017/token-activity
      PORT: 4052
    depends_on:
      - indexer-archive
      - indexer-token-contracts
      - mongo-token-activity
    networks:
      - db_token_activity_network
      - web_network

  nginx:
    image: nginx:1.15-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    restart: unless-stopped
    networks:
      - web_network
    depends_on:
      - indexer-token-activity
