version: '3'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=ethereum
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8002:5432'
      # command: ["postgres", "-c", "log_statement=all"]
