version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db/
    #   - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
    #   - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
    #   - ./.docker/mongodb/data/log/:/var/log/mongodb/
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    #   MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    # command: ['-f', '/etc/mongod.conf']
