version: '3'

networks:
  web-network:
    external:
      name: web-network
  db-network:
    name: db-network


services:

  archiver:
    build:
      context: ../.
      target: indexer
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=archiver
    environment:
      - RPC_ENDPOINT
      - MONGO_URI
    restart: unless-stopped
    networks:
      - db-network

  archive-query-node:
    build:
      context: ../.
      target: queryNode
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=archiver
    ports:
      - 4049:4050
    restart: unless-stopped
    networks:
      - web-network

  mongodb:
    networks:
      - db-network