version: '3'

networks:
  host:
    external: true
    driver: bridge

services:

  archiver:
    build:
      context: ../.
      target: archiver
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=archiver
    environment:
      - RPC_ENDPOINT
      - MONGO_URI
    restart: unless-stopped

  archive-query-node:
    build:
      context: ../.
      target: queryNode
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=archiver
    ports:
      - 4050:4050
    restart: unless-stopped
