version: '3'

services:
  archiver:
    build:
      context: ../.
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=archiver
    environment:
      RPC_ENDPOINT: 'TODO' # moonbeam
      MONGO_URI: 'mongodb://0.0.0.0:27017/ethereum-archive'
