version: '3'

services:

  archiver:
    build:
      context: ../.
      target: indexer
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=archiver
    environment:
      - RPC_ENDPOINT
      - MONGO_URI
    restart: unless-stopped

  archive-query-node:
    build:
      context: ../.
      target: queryNode
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=archiver
    ports:
      - 80:4050
    restart: unless-stopped
