version: '3'

services:
  archiver:
    build:
      context: ../.
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=archiver
    environment:
      EXTRACT_ENDPOINT: "TODO" # moonbeam
      LOAD_TYPE: mongo
      MONGO_URI: "mongodb://0.0.0.0:27017/ethereum-archive"