version: '3'

networks:
  web-network:
    external:
      name: web-network
  db-network:
    name: db-network

services:
  migrate:
    build:
      context: ../../.
      target: migrate
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=indexers/token-contracts
    environment:
      - DB_NAME
      - DB_HOST
      - DB_PORT
    depends_on:
      - db
    networks:
      - db-network

  indexer:
    build:
      context: ../../.
      target: indexer
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=indexers/token-contracts
    restart: unless-stopped
    environment:
      - ARCHIVE_GRAPH
      - DB_NAME
      - DB_HOST
      - DB_PORT
    volumes:
      volumes:
        - type: bind
          source: "${PWD}/data/last-indexed-block"
          target: "/base/indexers/token-contracts/last-indexed-block"
    networks:
      - db-network
      - web-network

  index-query-node:
    build:
      context: ../../.
      target: queryNode
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=indexers/token-contracts
    restart: unless-stopped
    ports:
      - 80:4050
    environment:
      - GQL_PORT=4050
      - DB_NAME
      - DB_HOST
      - DB_PORT
    networks:
      - db-network
      - web-network

  db:
    networks:
      - db-network

