version: '3'

services:
  migrate:
    build:
      context: ../../.
      target: migrate
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=indexers/token-contracts
    environment:
      - DB_NAME
      - DB_HOST
      - DB_PORT
  indexer:
    build:
      context: ../../.
      target: indexer
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=indexers/token-contracts
    restart: unless-stopped
    environment:
      - ARCHIVE_GRAPH
      - DB_NAME
      - DB_HOST
      - DB_PORT
  index-query-node:
    build:
      context: ../../.
      target: queryNode
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=indexers/token-contracts
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - GQL_PORT=80
      - DB_NAME
      - DB_HOST
      - DB_PORT
